on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: doc
      - run: pwd
      - run: rm -rf ./docs/docs.rs
      - run: cp -r ./target/doc ./docs/docs.rs
      - run: git add .
      - run: git commit -m 'Update docs'
